######################################################################
##
## Filename: BRAM_INST.udo
## Created on: 火 10月 06 22時10分10秒 JST 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
