######################################################################
##
## Filename: cpu_tb.udo
## Created on: 水 10月 07 03時03分44秒 JST 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
